// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDBAO-HoKw9Xv1iTUZiE6SysKoNNZA8jes',
    appId: '1:918555109164:web:467cc153c8c0464094ae89',
    messagingSenderId: '918555109164',
    projectId: 'vigilancia-d4457',
    authDomain: 'vigilancia-d4457.firebaseapp.com',
    databaseURL: 'https://vigilancia-d4457-default-rtdb.firebaseio.com',
    storageBucket: 'vigilancia-d4457.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDBAO-HoKw9Xv1iTUZiE6SysKoNNZA8jes',
    appId: '1:918555109164:android:467cc153c8c0464094ae89',
    messagingSenderId: '918555109164',
    projectId: 'vigilancia-d4457',
    databaseURL: 'https://vigilancia-d4457-default-rtdb.firebaseio.com',
    storageBucket: 'vigilancia-d4457.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDBAO-HoKw9Xv1iTUZiE6SysKoNNZA8jes',
    appId: '1:918555109164:ios:467cc153c8c0464094ae89',
    messagingSenderId: '918555109164',
    projectId: 'vigilancia-d4457',
    databaseURL: 'https://vigilancia-d4457-default-rtdb.firebaseio.com',
    storageBucket: 'vigilancia-d4457.firebasestorage.app',
    iosBundleId: 'com.example.vigilanciaApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDBAO-HoKw9Xv1iTUZiE6SysKoNNZA8jes',
    appId: '1:918555109164:ios:467cc153c8c0464094ae89',
    messagingSenderId: '918555109164',
    projectId: 'vigilancia-d4457',
    databaseURL: 'https://vigilancia-d4457-default-rtdb.firebaseio.com',
    storageBucket: 'vigilancia-d4457.firebasestorage.app',
    iosBundleId: 'com.example.vigilanciaApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDBAO-HoKw9Xv1iTUZiE6SysKoNNZA8jes',
    appId: '1:918555109164:web:467cc153c8c0464094ae89',
    messagingSenderId: '918555109164',
    projectId: 'vigilancia-d4457',
    authDomain: 'vigilancia-d4457.firebaseapp.com',
    databaseURL: 'https://vigilancia-d4457-default-rtdb.firebaseio.com',
    storageBucket: 'vigilancia-d4457.firebasestorage.app',
  );
}